<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::where('email', 'admin@xenonmotors.com')->first();
        $categories = Category::pluck('id', 'slug');

        $cars = [
            [
                'title' => '2024 Mercedes-Benz S-Class S500 4MATIC - Luxury Edition',
                'make' => 'Mercedes-Benz',
                'model' => 'S-Class S500',
                'year' => 2024,
                'category_id' => $categories['luxury'] ?? 1,
                'price' => 650000,
                'condition' => 'new',
                'mileage' => 500,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'Sedan',
                'exterior_color' => 'Obsidian Black',
                'interior_color' => 'Nappa Leather Beige',
                'doors' => 4,
                'seats' => 5,
                'description' => 'Brand new 2024 Mercedes-Benz S-Class S500 4MATIC. This flagship luxury sedan features the latest MBUX infotainment system, Executive Rear Seat Package, Burmester 4D surround sound, and advanced driver assistance systems. Full warranty included.',
                'features' => ['Panoramic Roof', 'Massage Seats', 'Night Vision', 'Air Suspension', 'Head-Up Display', '360 Camera'],
                'whatsapp_number' => '+971501234567',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2023 BMW X7 xDrive40i M Sport - 7 Seater',
                'make' => 'BMW',
                'model' => 'X7 xDrive40i',
                'year' => 2023,
                'category_id' => $categories['suv'] ?? 1,
                'price' => 420000,
                'condition' => 'used',
                'mileage' => 15000,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'SUV',
                'exterior_color' => 'Alpine White',
                'interior_color' => 'Cognac Leather',
                'doors' => 5,
                'seats' => 7,
                'description' => 'Stunning BMW X7 in pristine condition. M Sport package with 22-inch alloy wheels, panoramic sky lounge LED roof, Harman Kardon sound system, and BMW Live Cockpit Professional. Full service history with BMW.',
                'features' => ['Panoramic Roof', 'Apple CarPlay', 'Wireless Charging', 'Premium Sound', 'Heated Seats', 'Third Row Seating'],
                'whatsapp_number' => '+971502345678',
                'city' => 'Abu Dhabi',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2023 Porsche 911 Carrera S - Sport Chrono Package',
                'make' => 'Porsche',
                'model' => '911 Carrera S',
                'year' => 2023,
                'category_id' => $categories['sports'] ?? 1,
                'price' => 580000,
                'condition' => 'used',
                'mileage' => 8000,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'Coupe',
                'exterior_color' => 'Guards Red',
                'interior_color' => 'Black Leather',
                'doors' => 2,
                'seats' => 4,
                'description' => 'Iconic Porsche 911 Carrera S with Sport Chrono Package. Features PASM sport suspension, sport exhaust system, and PDK transmission. One owner, garage kept, with full Porsche service history.',
                'features' => ['Sport Exhaust', 'PASM', 'Sport Chrono', 'Bose Sound', 'Launch Control', 'Ceramic Brakes'],
                'whatsapp_number' => '+971503456789',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2024 Range Rover Autobiography LWB - First Edition',
                'make' => 'Land Rover',
                'model' => 'Range Rover Autobiography',
                'year' => 2024,
                'category_id' => $categories['suv'] ?? 1,
                'price' => 890000,
                'condition' => 'new',
                'mileage' => 200,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'SUV',
                'exterior_color' => 'Carpathian Grey',
                'interior_color' => 'Perlino/Ebony',
                'doors' => 5,
                'seats' => 5,
                'description' => 'The ultimate in luxury SUVs. Brand new Range Rover Autobiography Long Wheelbase with every option. Executive Class rear seats, Meridian Signature Sound, and the latest Pivi Pro infotainment.',
                'features' => ['Executive Seats', 'Refrigerator', 'Hot Stone Massage', 'Four-Zone Climate', 'Pixel LED', 'Terrain Response'],
                'whatsapp_number' => '+971504567890',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2022 Toyota Land Cruiser GXR V8 - Full Option',
                'make' => 'Toyota',
                'model' => 'Land Cruiser GXR',
                'year' => 2022,
                'category_id' => $categories['suv'] ?? 1,
                'price' => 285000,
                'condition' => 'used',
                'mileage' => 45000,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'SUV',
                'exterior_color' => 'Pearl White',
                'interior_color' => 'Beige Leather',
                'doors' => 5,
                'seats' => 8,
                'description' => 'Reliable Toyota Land Cruiser GXR V8 with full service history. Perfect for both city driving and desert adventures. Includes cool box, rear entertainment, and upgraded JBL sound system.',
                'features' => ['Cool Box', 'Rear Entertainment', 'JBL Sound', 'Sunroof', 'Leather Seats', 'Crawl Control'],
                'whatsapp_number' => '+971505678901',
                'city' => 'Sharjah',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
            [
                'title' => '2023 Audi RS7 Sportback - Carbon Package',
                'make' => 'Audi',
                'model' => 'RS7 Sportback',
                'year' => 2023,
                'category_id' => $categories['sports'] ?? 1,
                'price' => 520000,
                'condition' => 'used',
                'mileage' => 12000,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'Sportback',
                'exterior_color' => 'Nardo Grey',
                'interior_color' => 'Black Valcona Leather',
                'doors' => 5,
                'seats' => 5,
                'description' => 'Aggressive RS7 Sportback with Carbon Exterior Package. 600hp twin-turbo V8, quattro all-wheel drive, and RS sport suspension. Bang & Olufsen 3D sound system and full digital cockpit.',
                'features' => ['Carbon Package', 'B&O Sound', 'RS Exhaust', 'Dynamic Steering', 'Matrix LED', 'Sport Differential'],
                'whatsapp_number' => '+971506789012',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
            [
                'title' => '2024 Lexus LX 600 F Sport - GCC Specs',
                'make' => 'Lexus',
                'model' => 'LX 600 F Sport',
                'year' => 2024,
                'category_id' => $categories['suv'] ?? 1,
                'price' => 480000,
                'condition' => 'new',
                'mileage' => 0,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'SUV',
                'exterior_color' => 'Sonic Titanium',
                'interior_color' => 'Circuit Red',
                'doors' => 5,
                'seats' => 7,
                'description' => 'Brand new Lexus LX 600 F Sport with GCC specifications. Features the new twin-turbo V6, F Sport handling package, Mark Levinson audio, and Lexus Safety System+ 2.5.',
                'features' => ['Mark Levinson', 'F Sport Package', 'Adaptive Suspension', 'Multi-Terrain Select', 'Rear Seat Entertainment', 'Cool Box'],
                'whatsapp_number' => '+971507890123',
                'city' => 'Abu Dhabi',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
            [
                'title' => '2023 Tesla Model S Plaid - Full Self-Driving',
                'make' => 'Tesla',
                'model' => 'Model S Plaid',
                'year' => 2023,
                'category_id' => $categories['electric'] ?? 1,
                'price' => 450000,
                'condition' => 'used',
                'mileage' => 18000,
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'body_type' => 'Sedan',
                'exterior_color' => 'Midnight Silver',
                'interior_color' => 'White Interior',
                'doors' => 4,
                'seats' => 5,
                'description' => 'The fastest production car ever made. 1,020 horsepower, 0-100 km/h in under 2 seconds. Full Self-Driving capability, Yoke steering wheel, and premium interior. Supercharger network access included.',
                'features' => ['Full Self-Driving', 'Yoke Steering', 'Gaming Computer', 'Premium Audio', 'Glass Roof', 'Supercharging'],
                'whatsapp_number' => '+971508901234',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2022 Nissan Patrol Platinum - V8 Full Option',
                'make' => 'Nissan',
                'model' => 'Patrol Platinum',
                'year' => 2022,
                'category_id' => $categories['suv'] ?? 1,
                'price' => 245000,
                'condition' => 'used',
                'mileage' => 52000,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'SUV',
                'exterior_color' => 'Black',
                'interior_color' => 'Tan Leather',
                'doors' => 5,
                'seats' => 8,
                'description' => 'Popular Nissan Patrol Platinum with powerful V8 engine. Full option with leather seats, BOSE audio, around-view monitor, and hydraulic body motion control. Well maintained with service history.',
                'features' => ['BOSE Audio', 'Hydraulic Suspension', 'Around View', 'Rear Entertainment', 'Leather Seats', 'Intelligent Key'],
                'whatsapp_number' => '+971509012345',
                'city' => 'Ajman',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
            [
                'title' => '2023 Ford Mustang GT 5.0 V8 - Manual Transmission',
                'make' => 'Ford',
                'model' => 'Mustang GT',
                'year' => 2023,
                'category_id' => $categories['sports'] ?? 1,
                'price' => 185000,
                'condition' => 'used',
                'mileage' => 22000,
                'transmission' => 'manual',
                'fuel_type' => 'petrol',
                'body_type' => 'Coupe',
                'exterior_color' => 'Grabber Blue',
                'interior_color' => 'Ebony Leather',
                'doors' => 2,
                'seats' => 4,
                'description' => 'Pure American muscle! Ford Mustang GT with the legendary 5.0L V8 engine and rare 6-speed manual transmission. Performance package with MagneRide suspension and active exhaust.',
                'features' => ['MagneRide', 'Active Exhaust', 'Performance Pack', 'Recaro Seats', 'Digital Cluster', 'Track Apps'],
                'whatsapp_number' => '+971500123456',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
            [
                'title' => '2024 Rolls-Royce Ghost Black Badge',
                'make' => 'Rolls-Royce',
                'model' => 'Ghost Black Badge',
                'year' => 2024,
                'category_id' => $categories['luxury'] ?? 1,
                'price' => 1850000,
                'condition' => 'new',
                'mileage' => 100,
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'body_type' => 'Sedan',
                'exterior_color' => 'Black Diamond',
                'interior_color' => 'Mandarin Orange',
                'doors' => 4,
                'seats' => 5,
                'description' => 'The darkest, most powerful Ghost ever created. Black Badge edition with Bespoke Audio, Starlight Headliner, and Illuminated Fascia. Commissioned in an exclusive color combination.',
                'features' => ['Starlight Headliner', 'Bespoke Audio', 'Illuminated Fascia', 'Planar Suspension', 'Picnic Tables', 'Champagne Cooler'],
                'whatsapp_number' => '+971501112233',
                'city' => 'Dubai',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => true,
            ],
            [
                'title' => '2023 Honda Civic Type R - Track Ready',
                'make' => 'Honda',
                'model' => 'Civic Type R',
                'year' => 2023,
                'category_id' => $categories['sports'] ?? 1,
                'price' => 175000,
                'condition' => 'used',
                'mileage' => 8500,
                'transmission' => 'manual',
                'fuel_type' => 'petrol',
                'body_type' => 'Hatchback',
                'exterior_color' => 'Championship White',
                'interior_color' => 'Black/Red Suede',
                'doors' => 5,
                'seats' => 5,
                'description' => 'The ultimate hot hatchback. New generation Civic Type R with 330hp turbocharged engine and precision 6-speed manual. Track-focused suspension and Brembo brakes. Perfect condition.',
                'features' => ['Brembo Brakes', 'Adaptive Dampers', 'Rev Match', 'Honda LogR', 'Wireless CarPlay', 'Dual Zone AC'],
                'whatsapp_number' => '+971502223344',
                'city' => 'Sharjah',
                'country' => 'UAE',
                'is_published' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($cars as $carData) {
            Car::create(array_merge($carData, [
                'user_id' => $user->id,
            ]));
        }

        $this->command->info('Created 12 sample car listings!');
    }
}
